version: "2.0"
services:
  mysql:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dop
    ports:
      - "3306:3306"
#  solr:
#      image: solr
#      ports:
#       - "8983:8983"
#      volumes:
#        - data:/opt/solr/server/solr/mycores
#      entrypoint:
#        - docker-entrypoint.sh
#        - dop
#volumes:
#  data:
